# Generated by Django 5.1.2 on 2024-12-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersteps',
            unique_together={('user_id', 'date')},
        ),
    ]
